version: '3.7'

services: 
    client: 
        build:
            context: ./client
            dockerfile: Dockerfile
        image: client
        ports: 
            - 3000:3000
        depends_on: 
            - backend
    backend:
        build:
            context: ./wjproject
            dockerfile: Dockerfile
        image: wjproject
        ports: 
            - 8000:8000