version: '3.7'

services: 
    client: 
        image: client
        ports: 
            - 3000:3000
        depends_on: 
            - backend
    backend:
        image: wjproject
        ports: 
            - 8000:8000


